[package]
name = "actix_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
actix-web = "4.9.0"
core = { path = "../../core" }
glue = { path = "../../../../glue", features = ["actix"] }
