[package]
name = "glue"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", optional = true }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "2.0.3"

[features]
actix = ["dep:actix-web"]
